version: '3.8'
services:
  nest-app:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports: 
      - '3000:3000'
    networks:
      - common-networks
  mysql-container:
    image: mysql
    volumes:
      - /Users/v_lijianting/projects/docker-data/mysql
    environment:
      - MYSQL_DATABASE=aaa
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - common-networks
  redis-container:
    image: redis
    volumes:
      - /Users/v_lijianting/projects/docker-data/redis-test
    networks:
      - common-networks
networks:
  common-networks:
    driver: bridge