services:
  nest-app:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports: 
      - '3000:3000'
  mysql-container:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - /Users/v_lijianting/projects/docker-data/mysql
    environment:
      - MYSQL_DATABASE=aaa
      - MYSQL_ROOT_PASSWORD=root
  redis-container:
    image: redis
    ports:
      - '6370:6379'
    volumes:
      - /Users/v_lijianting/projects/docker-data/redis-test